import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: '#FAFAF7' },
  faixaFrete: {
    backgroundColor: '#7B9E4F',
    paddingVertical: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  faixaFreteTexto: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '700',
    textAlign: 'center',
  },
  marcaHome: {
    paddingHorizontal: 16,
    paddingTop: 14,
    alignItems: 'center',
  },
  marcaHomeTitulo: {
    color: '#6D8B3E',
    fontSize: 26,
    fontStyle: 'italic',
    fontWeight: '600',
    letterSpacing: 0.3,
    fontFamily: 'Georgia',
    textAlign: 'center',
  },
  banner: {
    height: 300,
    position: 'relative',
    marginHorizontal: 16,
    marginTop: 16,
    borderRadius: 24,
    overflow: 'hidden',
  },
  bannerImagem: { width: '100%', height: '160%' },
  bannerOverlay: {
    position: 'absolute',
    top: 0, left: 0, right: 0, bottom: 0,
    backgroundColor: 'rgba(32, 33, 27, 0.3)',
    justifyContent: 'center',
    padding: 24,
  },
  heroConteudo: {
    maxWidth: '90%',
    alignSelf: 'flex-start',
  },
  bannerTag: {
    color: '#e7f7d2',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1.1,
    textTransform: 'uppercase',
    marginBottom: 6,
  },
  bannerTitulo: { color: '#FFF', fontSize: 28, fontWeight: 'bold', lineHeight: 32, marginBottom: 12 },
  bannerDescricao: {
    color: '#FFF',
    fontSize: 14,
    fontWeight: '500',
    lineHeight: 20,
    marginBottom: 16,
    textShadowColor: 'rgba(0, 0, 0, 0.28)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  heroAcoes: { width: 145 },
  secao: { paddingHorizontal: 16, paddingTop: 20 },
  secaoHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
  secaoTitulo: { fontSize: 18, fontWeight: 'bold', color: '#333', marginBottom: 12 },
  verTodos: { fontSize: 13, color: '#7B9E4F', fontWeight: '600' },
  categoriasRow: { flexDirection: 'row', gap: 8, flexWrap: 'wrap' },
  categoriaCard: {
    paddingHorizontal: 16,
    paddingVertical: 7,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F0EDE8',
  },
  categoriaCardAtiva: {
    backgroundColor: '#7B9E4F',
  },
  categoriaTexto: { fontSize: 13, fontWeight: '500', color: '#666', textAlign: 'center' },
  categoriaTextoAtiva: { color: '#FFF', fontWeight: 'bold' },
  avisoApi: {
    fontSize: 12,
    color: '#7B9E4F',
    backgroundColor: '#F0F7E6',
    padding: 10,
    borderRadius: 8,
    marginBottom: 12,
  },
  loadingCard: {
    backgroundColor: '#FFF',
    borderRadius: 16,
    padding: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingTexto: { fontSize: 14, color: '#777' },
  switchRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#FFF',
    borderRadius: 12,
    padding: 16,
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 3,
  },
  switchLabel: { fontSize: 15, fontWeight: '600', color: '#333' },
  switchSub: { fontSize: 12, color: '#999', marginTop: 2 },
});
