import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: '#FAFAF7' },
  banner: { height: 320, position: 'relative' },
  bannerImagem: { width: '100%', height: '100%' },
  bannerOverlay: {
    position: 'absolute',
    top: 0, left: 0, right: 0, bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'flex-end',
    padding: 24,
    paddingBottom: 32,
  },
  bannerTag: { color: '#C8E6A0', fontSize: 12, fontWeight: 'bold', marginBottom: 8, letterSpacing: 1 },
  bannerTitulo: { color: '#FFF', fontSize: 28, fontWeight: 'bold', lineHeight: 36, marginBottom: 16 },
  secao: { paddingHorizontal: 16, paddingTop: 24 },
  secaoHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
  secaoTitulo: { fontSize: 18, fontWeight: 'bold', color: '#333', marginBottom: 12 },
  verTodos: { fontSize: 13, color: '#7B9E4F', fontWeight: '600' },
  categoriasRow: { flexDirection: 'row', gap: 12, flexWrap: 'wrap' },
  categoriaCard: {
    width: '30%',
    borderRadius: 14,
    padding: 16,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 80,
  },
  categoriaIcone: { fontSize: 28, marginBottom: 4 },
  categoriaTexto: { fontSize: 13, fontWeight: '600', color: '#444' },
  promoBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F0F7E6',
    margin: 16,
    borderRadius: 14,
    padding: 16,
    gap: 12,
    borderLeftWidth: 4,
    borderLeftColor: '#7B9E4F',
  },
  promoEmoji: { fontSize: 32 },
  promoTitulo: { fontSize: 16, fontWeight: 'bold', color: '#4A7A28' },
  promoSubtitulo: { fontSize: 12, color: '#6A8A48', marginTop: 2 },
  avisoApi: {
    fontSize: 12,
    color: '#7B9E4F',
    backgroundColor: '#F0F7E6',
    padding: 10,
    borderRadius: 8,
    marginBottom: 12,
  },
  loadingCard: {
    backgroundColor: '#FFF',
    borderRadius: 12,
    padding: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingTexto: { fontSize: 14, color: '#777' },
  switchRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#FFF',
    borderRadius: 12,
    padding: 16,
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 3,
  },
  switchLabel: { fontSize: 15, fontWeight: '600', color: '#333' },
  switchSub: { fontSize: 12, color: '#999', marginTop: 2 },
});
