import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: '#FAFAF7' },
  scroll: { padding: 16 },
  vazio: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 32 },
  vazioEmoji: { fontSize: 64, marginBottom: 16 },
  vazioTitulo: { fontSize: 20, fontWeight: 'bold', color: '#333', marginBottom: 6 },
  vazioSub: { fontSize: 14, color: '#999', marginBottom: 24 },
  cupomContainer: {
    backgroundColor: '#FFF',
    borderRadius: 14,
    padding: 16,
    marginBottom: 16,
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 3,
  },
  cupomLabel: { fontSize: 13, fontWeight: '600', color: '#555', marginBottom: 10 },
  cupomRow: { flexDirection: 'row', gap: 10 },
  cupomInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 14,
    color: '#333',
    backgroundColor: '#FAFAFA',
  },
  cupomInputErro: { borderColor: '#E85D4A' },
  cupomInputSucesso: { borderColor: '#4CAF50' },
  cupomBotao: {
    backgroundColor: '#7B9E4F',
    borderRadius: 10,
    paddingHorizontal: 18,
    justifyContent: 'center',
  },
  cupomBotaoSucesso: { backgroundColor: '#4CAF50' },
  cupomBotaoTexto: { color: '#FFF', fontWeight: 'bold', fontSize: 14 },
  cupomErro: { fontSize: 12, color: '#E85D4A', marginTop: 6 },
  cupomSucesso: { fontSize: 12, color: '#4CAF50', marginTop: 6, fontWeight: '600' },
  resumo: {
    backgroundColor: '#FFF',
    borderRadius: 14,
    padding: 16,
    marginBottom: 16,
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 3,
  },
  resumoTitulo: { fontSize: 16, fontWeight: 'bold', color: '#333', marginBottom: 14 },
  resumoLinha: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 10 },
  resumoChave: { fontSize: 14, color: '#666' },
  resumoValor: { fontSize: 14, color: '#333', fontWeight: '500' },
  divisor: { height: 1, backgroundColor: '#EEE', marginVertical: 10 },
  totalChave: { fontSize: 16, fontWeight: 'bold', color: '#222' },
  totalValor: { fontSize: 20, fontWeight: 'bold', color: '#7B9E4F' },
  freteAviso: {
    fontSize: 12,
    color: '#7B9E4F',
    backgroundColor: '#F0F7E6',
    padding: 10,
    borderRadius: 8,
    marginTop: 10,
  },
});