import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: '#FAFAF7' },
  imagem: { width: '100%', height: 300 },
  conteudo: { padding: 20 },
  categoriaRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 6 },
  categoria: { fontSize: 12, color: '#7B9E4F', fontWeight: 'bold', textTransform: 'uppercase', letterSpacing: 1 },
  volume: { fontSize: 12, color: '#999' },
  nome: { fontSize: 24, fontWeight: 'bold', color: '#222', marginBottom: 8 },
  avisoApi: {
    fontSize: 12,
    color: '#7B9E4F',
    backgroundColor: '#F0F7E6',
    padding: 10,
    borderRadius: 8,
    marginBottom: 12,
  },
  ratingRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 12 },
  avaliadores: { fontSize: 12, color: '#888' },
  preco: { fontSize: 28, fontWeight: 'bold', color: '#7B9E4F', marginBottom: 20 },
  quantidadeContainer: { marginBottom: 20 },
  quantidadeLabel: { fontSize: 14, color: '#555', marginBottom: 4 },
  quantidadeValor: { fontWeight: 'bold', color: '#7B9E4F' },
  slider: { width: '100%', height: 40 },
  sliderLabels: { flexDirection: 'row', justifyContent: 'space-between' },
  sliderLabel: { fontSize: 11, color: '#AAA' },
  abas: { flexDirection: 'row', marginBottom: 12, borderBottomWidth: 1, borderBottomColor: '#EEE' },
  aba: { paddingHorizontal: 16, paddingVertical: 10, marginRight: 4 },
  abaAtiva: { borderBottomWidth: 2, borderBottomColor: '#7B9E4F' },
  abaTexto: { fontSize: 14, color: '#999' },
  abaTextoAtivo: { color: '#7B9E4F', fontWeight: 'bold' },
  textoConteudo: { fontSize: 14, color: '#555', lineHeight: 22, marginBottom: 16 },
  selosRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 20 },
  selo: { backgroundColor: '#F0F7E6', borderRadius: 20, paddingHorizontal: 12, paddingVertical: 5 },
  seloTexto: { fontSize: 12, color: '#4A7A28', fontWeight: '500' },
  sucessoBanner: {
    backgroundColor: '#E8F5E9',
    borderRadius: 10,
    padding: 12,
    marginBottom: 12,
    alignItems: 'center',
  },
  sucessoTexto: { color: '#2E7D32', fontSize: 14, fontWeight: '600' },
  semProduto: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 32 },
  semProdutoTexto: { fontSize: 16, color: '#999', marginBottom: 16 },
});
