import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: '#FAFAF7' },
  scroll: { padding: 16 },
  hero: { height: 200, borderRadius: 16, overflow: 'hidden', marginBottom: 16 },
  heroImagem: { width: '100%', height: '100%' },
  heroOverlay: {
    position: 'absolute',
    top: 0, left: 0, right: 0, bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  heroLogo: { fontSize: 26, fontWeight: 'bold', color: '#FFF', marginBottom: 6 },
  heroSlogan: { fontSize: 13, color: '#C8E6A0', letterSpacing: 1 },
  statsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 20,
  },
  statCard: {
    width: '48%',
    backgroundColor: '#FFF',
    borderRadius: 12,
    padding: 12,
    alignItems: 'center',
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 3,
  },
  statNumero: { fontSize: 15, fontWeight: 'bold', color: '#7B9E4F', textAlign: 'center' },
  statLabel: { fontSize: 10, color: '#999', marginTop: 4, textAlign: 'center' },
  abasContainer: {
    flexDirection: 'row',
    backgroundColor: '#FFF',
    borderRadius: 12,
    padding: 4,
    marginBottom: 12,
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 3,
  },
  aba: { flex: 1, paddingVertical: 10, alignItems: 'center', borderRadius: 10 },
  abaAtiva: { backgroundColor: '#7B9E4F' },
  abaTexto: { fontSize: 13, color: '#888', fontWeight: '500' },
  abaTextoAtivo: { color: '#FFF', fontWeight: 'bold' },
  secao: {
    backgroundColor: '#FFF',
    borderRadius: 14,
    padding: 16,
    marginBottom: 16,
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 3,
  },
  textoMissao: { fontSize: 14, color: '#555', lineHeight: 23 },
  timelineItem: { flexDirection: 'row', marginBottom: 4 },
  timelineLinha: { alignItems: 'center', width: 24, marginRight: 12 },
  timelinePonto: { width: 12, height: 12, borderRadius: 6, backgroundColor: '#7B9E4F', marginTop: 4 },
  timelineConector: { width: 2, flex: 1, backgroundColor: '#D8EDBB', marginTop: 4, marginBottom: -4, minHeight: 30 },
  timelineConteudo: { flex: 1, paddingBottom: 16 },
  timelineAno: { fontSize: 13, fontWeight: 'bold', color: '#7B9E4F' },
  timelineEvento: { fontSize: 13, color: '#555', marginTop: 2, lineHeight: 18 },
  valorCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 16,
    gap: 12,
  },
  valorIcone: { fontSize: 28, marginTop: 2 },
  valorTitulo: { fontSize: 15, fontWeight: 'bold', color: '#333', marginBottom: 4 },
  valorDesc: { fontSize: 13, color: '#666', lineHeight: 18 },
  avaliacaoContainer: {
    backgroundColor: '#FFF',
    borderRadius: 14,
    padding: 16,
    marginBottom: 16,
    alignItems: 'center',
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 3,
  },
  avaliacaoTitulo: { fontSize: 15, fontWeight: 'bold', color: '#333', marginBottom: 8 },
  avaliacaoValor: { fontSize: 22, color: '#F5A623', marginBottom: 4, letterSpacing: 2 },
  slider: { width: '100%', height: 40 },
  sliderLabels: { flexDirection: 'row', justifyContent: 'space-between', width: '100%' },
  sliderLabel: { fontSize: 11, color: '#AAA' },
  rodape: { textAlign: 'center', fontSize: 11, color: '#CCC', marginTop: 8 },
});
