import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: '#FAFAF7' },
  scroll: { padding: 16 },
  hero: { height: 210, borderRadius: 20, overflow: 'hidden', marginBottom: 16 },
  heroImagem: { width: '100%', height: '100%' },
  heroOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(16, 18, 12, 0.34)',
    justifyContent: 'flex-end',
    alignItems: 'flex-start',
    paddingHorizontal: 22,
    paddingVertical: 22,
  },
  heroTag: {
    color: '#E5F3C8',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginBottom: 8,
  },
  heroLogo: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#FFF',
    marginBottom: 8,
    lineHeight: 26,
    maxWidth: '72%',
  },
  heroSlogan: {
    fontSize: 14,
    color: '#F6F3EC',
    lineHeight: 20,
    maxWidth: '78%',
    textShadowColor: 'rgba(0, 0, 0, 0.18)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  statsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 20,
  },
  statCard: {
    width: '48%',
    backgroundColor: '#FFF',
    borderRadius: 12,
    padding: 12,
    alignItems: 'center',
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 3,
  },
  statNumero: { fontSize: 15, fontWeight: 'bold', color: '#7B9E4F', textAlign: 'center' },
  statLabel: { fontSize: 10, color: '#999', marginTop: 4, textAlign: 'center' },
  abasContainer: {
    flexDirection: 'row',
    backgroundColor: '#FFF',
    borderRadius: 12,
    padding: 4,
    marginBottom: 12,
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 3,
  },
  aba: { flex: 1, paddingVertical: 10, alignItems: 'center', borderRadius: 10 },
  abaAtiva: { backgroundColor: '#7B9E4F' },
  abaTexto: { fontSize: 13, color: '#888', fontWeight: '500' },
  abaTextoAtivo: { color: '#FFF', fontWeight: 'bold' },
  secao: {
    backgroundColor: '#FFF',
    borderRadius: 14,
    padding: 16,
    marginBottom: 16,
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 3,
  },
  textoMissao: { fontSize: 14, color: '#555', lineHeight: 23 },
  valorCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 16,
    gap: 12,
  },
  valorIcone: { fontSize: 28, marginTop: 2 },
  valorTitulo: { fontSize: 15, fontWeight: 'bold', color: '#333', marginBottom: 4 },
  valorDesc: { fontSize: 13, color: '#666', lineHeight: 18 },
  localizacaoTitulo: { fontSize: 15, fontWeight: 'bold', color: '#333', marginBottom: 8 },
  localizacaoBox: {
    borderRadius: 12,
    backgroundColor: '#F4F8EC',
    borderWidth: 1,
    borderColor: '#D8EDBB',
    padding: 12,
    marginTop: 14,
  },
  localizacaoLinha: { fontSize: 13, color: '#4C5F35', lineHeight: 19, marginBottom: 6 },
  localizacaoAjuda: { fontSize: 12, color: '#777', lineHeight: 18, marginTop: 12 },
  avaliacaoContainer: {
    backgroundColor: '#FFF',
    borderRadius: 14,
    padding: 16,
    marginBottom: 16,
    alignItems: 'center',
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 3,
  },
  avaliacaoTitulo: { fontSize: 15, fontWeight: 'bold', color: '#333', marginBottom: 8 },
  avaliacaoValor: { fontSize: 22, color: '#F5A623', marginBottom: 4, letterSpacing: 2 },
  slider: { width: '100%', height: 40 },
  sliderLabels: { flexDirection: 'row', justifyContent: 'space-between', width: '100%' },
  sliderLabel: { fontSize: 11, color: '#AAA' },
  rodape: { textAlign: 'center', fontSize: 11, color: '#CCC', marginTop: 8 },
});
