import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: '#FAFAF7' },
  scroll: { padding: 16 },
  avatarContainer: { alignItems: 'center', paddingVertical: 24 },
  avatar: {
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: '#7B9E4F',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
    elevation: 4,
    shadowColor: '#7B9E4F',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  avatarLetra: { fontSize: 38, fontWeight: 'bold', color: '#FFF' },
  avatarNome: { fontSize: 20, fontWeight: 'bold', color: '#222', marginBottom: 4 },
  avatarEmail: { fontSize: 13, color: '#888' },
  secao: {
    backgroundColor: '#FFF',
    borderRadius: 14,
    padding: 16,
    marginBottom: 16,
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 3,
  },
  secaoHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 14 },
  secaoTitulo: { fontSize: 16, fontWeight: 'bold', color: '#333', marginBottom: 14 },
  editarTexto: { fontSize: 13, color: '#7B9E4F', fontWeight: '600' },
  campo: { marginBottom: 14 },
  campoLabel: { fontSize: 12, color: '#999', marginBottom: 4, fontWeight: '600', textTransform: 'uppercase', letterSpacing: 0.5 },
  campoInput: {
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 15,
    color: '#333',
    backgroundColor: '#FAFAFA',
  },
  campoReadonly: { backgroundColor: '#F5F5F5', borderColor: '#EFEFEF', color: '#555' },
  switchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F5F5F5',
  },
  switchLabel: { fontSize: 14, fontWeight: '500', color: '#333' },
  switchSub: { fontSize: 11, color: '#999', marginTop: 2 },
  pedidoCard: {
    borderWidth: 1,
    borderColor: '#F0EDE8',
    borderRadius: 10,
    padding: 12,
    marginBottom: 10,
  },
  pedidoHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 6 },
  pedidoId: { fontSize: 14, fontWeight: 'bold', color: '#333' },
  pedidoStatus: { borderRadius: 20, paddingHorizontal: 10, paddingVertical: 3 },
  pedidoStatusTexto: { fontSize: 11, fontWeight: 'bold' },
  pedidoRodape: { flexDirection: 'row', justifyContent: 'space-between' },
  pedidoData: { fontSize: 12, color: '#999' },
  pedidoTotal: { fontSize: 13, fontWeight: 'bold', color: '#7B9E4F' },
});