export const PRODUTOS = [
  {
    id: '1',
    nome: 'Óleo de Argan Puro',
    categoria: 'Cabelo',
    preco: 89.9,
    nota: 4.8,
    destaque: true,
    imagem: 'https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?w=400',
    descricao: 'Óleo de argan 100% puro e natural, extraído a frio do fruto da argan tree marroquina. Nutre, hidrata e dá brilho intenso aos cabelos. Rico em vitamina E e ácidos graxos essenciais.',
    ingredientes: 'Argania Spinosa Kernel Oil',
    volume: '60ml',
    avaliadores: 312,
  },
  {
    id: '2',
    nome: 'Máscara Capilar Manteiga de Karité',
    categoria: 'Cabelo',
    preco: 64.9,
    nota: 4.6,
    destaque: false,
    imagem: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400',
    descricao: 'Máscara profunda com manteiga de karité e extrato de abacate. Restaura a fibra capilar danificada, reduz o frizz e devolve o brilho natural. Ideal para cabelos secos e quimicamente tratados.',
    ingredientes: 'Butyrospermum Parkii, Persea Gratissima, Panthenol',
    volume: '250g',
    avaliadores: 198,
  },
  {
    id: '3',
    nome: 'Sérum Vitamina C Facial',
    categoria: 'Rosto',
    preco: 119.0,
    nota: 4.9,
    destaque: true,
    imagem: 'https://images.unsplash.com/photo-1570194065650-d99fb4b38b06?w=400',
    descricao: 'Sérum concentrado com 20% de vitamina C estabilizada, ácido hialurônico e niacinamida. Ilumina, uniformiza o tom da pele e combate os sinais de envelhecimento. Textura leve de absorção rápida.',
    ingredientes: 'Ascorbic Acid 20%, Hyaluronic Acid, Niacinamide, Aloe Vera',
    volume: '30ml',
    avaliadores: 445,
  },
  {
    id: '4',
    nome: 'Hidratante Corporal Coco & Baunilha',
    categoria: 'Corpo',
    preco: 52.9,
    nota: 4.5,
    destaque: false,
    imagem: 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=400',
    descricao: 'Loção hidratante com óleo de coco virgem e extrato de baunilha do Tahiti. Hidratação profunda por até 24h, aroma delicioso e pele macia ao toque.',
    ingredientes: 'Cocos Nucifera Oil, Vanilla Planifolia, Shea Butter, Aloe Vera',
    volume: '300ml',
    avaliadores: 267,
  },
  {
    id: '5',
    nome: 'Shampoo Sólido Lavanda',
    categoria: 'Cabelo',
    preco: 38.5,
    nota: 4.4,
    destaque: false,
    imagem: 'https://images.unsplash.com/photo-1584305574647-0cc949a2bb9f?w=400',
    descricao: 'Shampoo sólido com extrato de lavanda, pH balanceado e fórmula vegana. Zero plástico na embalagem, equivale a 3 frascos de shampoo líquido. Suave e eficiente para cabelos normais.',
    ingredientes: 'Sodium Cocoyl Isethionate, Lavandula Angustifolia, Panthenol',
    volume: '80g',
    avaliadores: 153,
  },
  {
    id: '6',
    nome: 'Esfoliante Corporal Café Verde',
    categoria: 'Corpo',
    preco: 44.9,
    nota: 4.3,
    destaque: false,
    imagem: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=400',
    descricao: 'Esfoliante corporal com grânulos de café verde e óleo de jojoba. Remove células mortas, estimula a circulação e deixa a pele renovada e perfumada.',
    ingredientes: 'Coffea Arabica Seed, Simmondsia Chinensis Oil, Sucrose',
    volume: '200g',
    avaliadores: 89,
  },
];

export const CATEGORIAS = ['Todos', 'Cabelo', 'Rosto', 'Corpo'];