export const PRODUTOS = [
  {
    id: 'local-1',
    nome: 'Kit Salvatore Progressiva Profissional Blue Gold 2x1000ml',
    categoria: 'Cabelo',
    preco: 380,
    precoOriginal: 445,
    nota: 4.8,
    destaque: true,
    disponivel: true,
    imagem: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=800',
    descricao: 'Kit profissional para cuidados capilares, inspirado no catálogo de cosméticos multimarca da Brilho Natural Shop.',
    ingredientes: 'Consulte a embalagem do produto para composição completa e modo de uso.',
    volume: '2x1000ml',
    avaliadores: 120,
  },
  {
    id: 'local-2',
    nome: "Kit Salvatore O'ka Profissional Shampoo e Conditioner",
    categoria: 'Cabelo',
    preco: 269.9,
    precoOriginal: 319.9,
    nota: 4.8,
    destaque: true,
    disponivel: true,
    imagem: 'https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=800',
    descricao: 'Linha profissional para rotina capilar com foco em cuidado, limpeza e tratamento.',
    ingredientes: 'Consulte a embalagem do produto para composição completa e modo de uso.',
    volume: '2x300ml',
    avaliadores: 94,
  },
  {
    id: 'local-3',
    nome: "Victoria's Secret Perfume Blush 250ml",
    categoria: 'Perfumes',
    preco: 119.9,
    precoOriginal: 149.9,
    nota: 4.9,
    destaque: true,
    disponivel: true,
    imagem: 'https://images.unsplash.com/photo-1541643600914-78b084683601?w=800',
    descricao: 'Fragrância corporal inspirada nas linhas de perfumes e body splashes disponíveis na loja.',
    ingredientes: 'Consulte a embalagem do produto para composição completa e modo de uso.',
    volume: '250ml',
    avaliadores: 210,
  },
  {
    id: 'local-4',
    nome: "Victoria's Secret Body Cream Kiss 200ml",
    categoria: 'Corpo',
    preco: 96.9,
    precoOriginal: 0,
    nota: 4.7,
    destaque: false,
    disponivel: true,
    imagem: 'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=800',
    descricao: 'Hidratante corporal para complementar a rotina de cuidado e perfumação diária.',
    ingredientes: 'Consulte a embalagem do produto para composição completa e modo de uso.',
    volume: '200ml',
    avaliadores: 132,
  },
  {
    id: 'local-5',
    nome: 'Revlon UniqOne All in One Shampoo Professional',
    categoria: 'Cabelo',
    preco: 82.9,
    precoOriginal: 99.9,
    nota: 4.7,
    destaque: false,
    disponivel: true,
    imagem: 'https://images.unsplash.com/photo-1619451334792-150fd785ee74?w=800',
    descricao: 'Shampoo profissional para diferentes rotinas de cuidado capilar.',
    ingredientes: 'Consulte a embalagem do produto para composição completa e modo de uso.',
    volume: '490ml',
    avaliadores: 76,
  },
  {
    id: 'local-6',
    nome: 'Joico Moisture Recovery Kit Shampoo e Conditioner',
    categoria: 'Cabelo',
    preco: 329.9,
    precoOriginal: 369.9,
    nota: 4.9,
    destaque: true,
    disponivel: true,
    imagem: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=800',
    descricao: 'Kit capilar com proposta de cuidado para fios ressecados e rotina profissional.',
    ingredientes: 'Consulte a embalagem do produto para composição completa e modo de uso.',
    volume: '2x300ml',
    avaliadores: 88,
  },
  {
    id: 'local-7',
    nome: 'Redken All Soft Conditioner Professional',
    categoria: 'Cabelo',
    preco: 149.9,
    precoOriginal: 179.9,
    nota: 4.8,
    destaque: false,
    disponivel: false,
    imagem: 'https://images.unsplash.com/photo-1556227834-09f1de7a7d14?w=800',
    descricao: 'Condicionador profissional voltado para maciez e rotina de tratamento capilar.',
    ingredientes: 'Consulte a embalagem do produto para composição completa e modo de uso.',
    volume: '300ml',
    avaliadores: 67,
  },
  {
    id: 'local-8',
    nome: 'Schwarzkopf Bonacure Hair Therapy Shampoo',
    categoria: 'Cabelo',
    preco: 109.9,
    precoOriginal: 0,
    nota: 4.6,
    destaque: false,
    disponivel: true,
    imagem: 'https://images.unsplash.com/photo-1626784215021-2e39ccf971cd?w=800',
    descricao: 'Shampoo profissional alinhado ao mix multimarca de cuidados capilares.',
    ingredientes: 'Consulte a embalagem do produto para composição completa e modo de uso.',
    volume: '250ml',
    avaliadores: 59,
  },
  {
    id: 'local-9',
    nome: 'Berioska Babaria Shampoo',
    categoria: 'Cabelo',
    preco: 54.9,
    precoOriginal: 0,
    nota: 4.5,
    destaque: false,
    disponivel: true,
    imagem: 'https://images.unsplash.com/photo-1607006483225-989e8c7d0f50?w=800',
    descricao: 'Shampoo para cuidados diários, representando linhas comerciais presentes na loja.',
    ingredientes: 'Consulte a embalagem do produto para composição completa e modo de uso.',
    volume: '400ml',
    avaliadores: 41,
  },
  {
    id: 'local-10',
    nome: 'Máscara Capilar Profissional de Tratamento',
    categoria: 'Cabelo',
    preco: 89.9,
    precoOriginal: 109.9,
    nota: 4.7,
    destaque: false,
    disponivel: true,
    imagem: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=800',
    descricao: 'Máscara de tratamento para rotinas de cuidado capilar em casa ou no salão.',
    ingredientes: 'Consulte a embalagem do produto para composição completa e modo de uso.',
    volume: '500g',
    avaliadores: 73,
  },
];

export const CATEGORIAS = ['Todos', 'Cabelo', 'Corpo', 'Perfumes', 'Rosto', 'Outros'];
