import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: '#FAFAF7' },
  scroll: { padding: 16 },
  secaoTitulo: { fontSize: 18, fontWeight: 'bold', color: '#333', marginBottom: 14 },
  canaisGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 24,
  },
  canalCard: {
    width: '47%',
    borderRadius: 14,
    padding: 14,
    alignItems: 'flex-start',
  },
  canalIcone: { fontSize: 26, marginBottom: 6 },
  canalTitulo: { fontSize: 12, fontWeight: 'bold', color: '#555', textTransform: 'uppercase', letterSpacing: 0.5, marginBottom: 4 },
  canalValor: { fontSize: 12, color: '#444', lineHeight: 16 },
  formulario: {
    backgroundColor: '#FFF',
    borderRadius: 14,
    padding: 16,
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 3,
  },
  formularioTitulo: { fontSize: 16, fontWeight: 'bold', color: '#333', marginBottom: 16 },
  sucessoBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#E8F5E9',
    borderRadius: 10,
    padding: 14,
    marginBottom: 16,
    gap: 12,
  },
  sucessoEmoji: { fontSize: 28 },
  sucessoTitulo: { fontSize: 14, fontWeight: 'bold', color: '#2E7D32' },
  sucessoSub: { fontSize: 12, color: '#4CAF50' },
  campo: { marginBottom: 14 },
  campoLabel: { fontSize: 12, color: '#888', fontWeight: '600', marginBottom: 6, textTransform: 'uppercase', letterSpacing: 0.5 },
  input: {
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 11,
    fontSize: 15,
    color: '#333',
    backgroundColor: '#FAFAFA',
  },
  pickerWrapper: {
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 10,
    backgroundColor: '#FAFAFA',
    overflow: 'hidden',
  },
  picker: { height: 50, color: '#333' },
  textarea: {
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 11,
    fontSize: 15,
    color: '#333',
    backgroundColor: '#FAFAFA',
    minHeight: 120,
  },
  contadorCaracteres: { fontSize: 11, color: '#BBB', textAlign: 'right', marginTop: 4 },
});