import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: '#FAFAF7' },
  scroll: { padding: 16 },
  secaoTitulo: { fontSize: 18, fontWeight: 'bold', color: '#333', marginBottom: 14 },
  secaoSubtitulo: { fontSize: 13, color: '#666', lineHeight: 19, marginTop: -6, marginBottom: 18 },
  loadingCard: {
    backgroundColor: '#FFF',
    borderRadius: 14,
    padding: 16,
    marginBottom: 18,
  },
  loadingTexto: { fontSize: 14, color: '#777' },
  erroBanner: {
    fontSize: 12,
    color: '#C14F41',
    backgroundColor: '#FDEDEA',
    borderRadius: 10,
    padding: 12,
    marginBottom: 14,
  },
  canaisGrid: {
    gap: 10,
    marginBottom: 24,
  },
  canalCard: {
    borderRadius: 14,
    padding: 14,
    backgroundColor: '#FFF',
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 3,
  },
  canalTitulo: { fontSize: 12, fontWeight: 'bold', color: '#555', textTransform: 'uppercase', letterSpacing: 0.5, marginBottom: 6 },
  canalDescricao: { fontSize: 13, color: '#666', lineHeight: 18, marginBottom: 6 },
  canalValor: { fontSize: 14, color: '#333', fontWeight: '600', lineHeight: 18 },
  formulario: {
    backgroundColor: '#FFF',
    borderRadius: 14,
    padding: 16,
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 3,
  },
  formularioTitulo: { fontSize: 16, fontWeight: 'bold', color: '#333', marginBottom: 16 },
  formularioAjuda: { fontSize: 12, color: '#777', marginTop: -6, marginBottom: 16, lineHeight: 18 },
  sucessoBanner: {
    backgroundColor: '#E8F5E9',
    borderRadius: 10,
    padding: 14,
    marginBottom: 16,
  },
  sucessoTitulo: { fontSize: 14, fontWeight: 'bold', color: '#2E7D32', marginBottom: 4 },
  sucessoSub: { fontSize: 12, color: '#4CAF50', lineHeight: 18 },
  campo: { marginBottom: 14 },
  campoLabel: { fontSize: 12, color: '#888', fontWeight: '600', marginBottom: 6, textTransform: 'uppercase', letterSpacing: 0.5 },
  input: {
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 11,
    fontSize: 15,
    color: '#333',
    backgroundColor: '#FAFAFA',
  },
  selectWrapper: {
    position: 'relative',
    zIndex: 20,
  },
  selectButton: {
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 10,
    backgroundColor: '#FAFAFA',
    minHeight: 56,
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  selectButtonAberto: {
    borderColor: '#B7C89A',
  },
  selectButtonTexto: {
    flex: 1,
    fontSize: 15,
    color: '#333',
    fontWeight: '500',
    paddingRight: 12,
  },
  selectButtonIcone: {
    color: '#333',
    fontSize: 14,
    fontWeight: '700',
  },
  selectLista: {
    marginTop: 8,
    borderWidth: 1,
    borderColor: '#D9D9D9',
    borderRadius: 12,
    backgroundColor: '#FFF',
    overflow: 'hidden',
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
  },
  selectOpcao: {
    paddingHorizontal: 16,
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#F1EEE9',
  },
  selectOpcaoUltima: {
    borderBottomWidth: 0,
  },
  selectOpcaoAtiva: {
    backgroundColor: '#F0F7E6',
  },
  selectOpcaoTexto: {
    fontSize: 15,
    color: '#333',
    lineHeight: 20,
  },
  selectOpcaoTextoAtivo: {
    color: '#6D8B3E',
    fontWeight: '700',
  },
  textarea: {
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 11,
    fontSize: 15,
    color: '#333',
    backgroundColor: '#FAFAFA',
    minHeight: 120,
  },
  contadorCaracteres: { fontSize: 11, color: '#BBB', textAlign: 'right', marginTop: 4 },
  protocoloTexto: { fontSize: 12, color: '#6D8B3E', fontWeight: '600', marginBottom: 14 },
  faqCard: {
    backgroundColor: '#FFF',
    borderRadius: 14,
    padding: 16,
    marginTop: 18,
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 3,
  },
  faqItem: {
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#EFEAE1',
  },
  faqPergunta: { fontSize: 14, fontWeight: '600', color: '#333', marginBottom: 4 },
  faqResposta: { fontSize: 13, color: '#666', lineHeight: 19 },
});
