import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: '#FAFAF7' },
  scroll: { padding: 16 },
  card: {
    backgroundColor: '#FFF',
    borderRadius: 14,
    padding: 16,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 3,
  },
  cardTitulo: { fontSize: 16, fontWeight: 'bold', color: '#333', marginBottom: 14 },
  itemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#F3F0EB',
    paddingVertical: 10,
  },
  itemNome: { fontSize: 14, fontWeight: '600', color: '#333' },
  itemMeta: { fontSize: 12, color: '#888', marginTop: 3 },
  itemPreco: { fontSize: 14, fontWeight: 'bold', color: '#7B9E4F' },
  linhaResumo: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 10 },
  chaveResumo: { fontSize: 14, color: '#666' },
  valorResumo: { fontSize: 14, color: '#333', fontWeight: '500' },
  valorDesconto: { fontSize: 14, color: '#4CAF50', fontWeight: '600' },
  freteInfo: { fontSize: 12, color: '#7B9E4F', marginBottom: 10 },
  divisor: { height: 1, backgroundColor: '#EEE', marginVertical: 10 },
  totalChave: { fontSize: 16, fontWeight: 'bold', color: '#222' },
  totalValor: { fontSize: 20, fontWeight: 'bold', color: '#7B9E4F' },
  campoLabel: {
    fontSize: 12,
    color: '#888',
    marginBottom: 6,
    marginTop: 10,
    textTransform: 'uppercase',
    fontWeight: '600',
    letterSpacing: 0.5,
  },
  input: {
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 14,
    color: '#333',
    backgroundColor: '#FAFAFA',
  },
  cepRow: { flexDirection: 'row', alignItems: 'flex-end', gap: 10 },
  botaoCep: { width: 132 },
  linhaCampos: { flexDirection: 'row', gap: 12 },
  campoFlex: { flex: 1 },
  campoUf: { width: 90 },
  erroTexto: { fontSize: 12, color: '#E85D4A', marginTop: 8, fontWeight: '500' },
  sucessoContainer: {
    flex: 1,
    padding: 24,
    justifyContent: 'center',
    alignItems: 'center',
  },
  sucessoEmoji: { fontSize: 62, marginBottom: 12 },
  sucessoTitulo: { fontSize: 24, fontWeight: 'bold', color: '#2E7D32', marginBottom: 8 },
  sucessoTexto: { fontSize: 14, color: '#555', textAlign: 'center', marginBottom: 10 },
  sucessoResumo: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#7B9E4F',
    marginBottom: 24,
  },
});
